# Generated by Django 3.2.3 on 2021-12-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_url', models.CharField(max_length=300)),
                ('shortener_url', models.CharField(max_length=100)),
                ('http_type', models.CharField(choices=[('0', 'http'), ('1', 'https')], max_length=1)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'URL_MAPPING',
            },
        ),
    ]
