# Generated by Django 2.2.17 on 2021-12-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_mapping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlmapping',
            name='http_type',
        ),
        migrations.AlterField(
            model_name='urlmapping',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
